---
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  CMAKE_BUILD_TYPE: Release

icc:
  tags:
    - perun
  image:
    name: intel/oneapi-hpckit
    entrypoint: []
  variables:
    CC: icc
  script:
    - . /root/.oneapi_env_vars
    - apt-get update
    - apt-get install -y python3-pip
    - pip3 install jinja2
    - make test

gcc:
  image: registry.gitlab.com/kamcuk/builder
  variables:
    CC: gcc
  script:
    - pacman -Sy --noconfirm python-jinja
    - make test
    - mv _build/gcc/include ./include
  artifacts:
    paths:
      - include

clang:
  image: registry.gitlab.com/kamcuk/builder
  variables:
    CC: clang
  script:
    - pacman -Sy --noconfirm python-jinja
    - make test

alpine:
  image: registry.gitlab.com/kamcuk/builder:alpine
  script:
    - apk add py3-jinja2
    - make test CONFARGS=-UCKD_DEV

coverage:
  image: registry.gitlab.com/kamcuk/builder
  script:
    - pacman -Sy --noconfirm python-jinja gcovr
    - make coverage
