---
image: registry.gitlab.com/kamcuk/builder
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  CMAKE_BUILD_TYPE: Release

icc_test:
  tags:
    - perun
  image:
    name: intel/oneapi-hpckit
    entrypoint: []
  variables:
    CC: icc
  script:
    - . /root/.oneapi_env_vars
    - apt-get update
    - apt-get install -y python3-jinja2
    - make test

gcc_test:
  variables:
    CC: gcc
  script:
    - pacman -Sy --noconfirm python-jinja
    - make test

clang_test:
  variables:
    CC: clang
  script:
    - pacman -Sy --noconfirm python-jinja
    - make test

alpine_test:
  image: registry.gitlab.com/kamcuk/builder:alpine
  script:
    - apk add py3-jinja2
    - make test
