---
on:
  - push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target:
          - alpine
          - gcc
          - clang
          - intel
    runs-on: nomadtools mem=3000
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: hadolint/hadolint-action@v3.1.0
      - run: DOCKER_BUILDKIT=1 docker build --pull --target ${{matrix.target}} .

